### ISSUE TITLE
Course titles with slashes are interpreted as subdirectories

### ISSUE THREAD

**Issue by lhoenig** [Emily3403/isisdl#14]
For course titles with slashes '/', subdirectories will be created: for example for the course with title `MI1 (WS22/23)`, a directory `MI1 (WS22` will be created containing a directory `23)`, where the course content will be stored.

Slashes should be replaced with a nonsemantic char, for example an underscore or space.

**Comment by lhoenig** [comment]
I haven't tested it but if course titles are interpreted literally as paths, this could also imply a directory traversal vulnerability if the course title includes ".." (which is unlikely but possible)

**Comment by lhoenig** [comment]
I ran `isisdl --sync` and now I get this error:
<img width="1200" alt="Screenshot 2022-10-22 at 20 08 49" src="https://user-images.githubusercontent.com/4353030/197356187-b03d1d27-518f-49b0-a970-66fdb51ace9f.png">

**Comment by lhoenig** [comment]
Also, I actually found a course having ".." in its title: https://isis.tu-berlin.de/course/view.php?id=30165
But cannot test it at the moment due to the error above..

**Comment by lhoenig** [comment]
One more thing: for sanitizing the course names, [python-slugify](https://pypi.org/project/python-slugify/) could be a good option.

**Comment by lhoenig** [comment]
Ok, I found that there is a safe-filename option that I apparently disabled for some reason. Then I have the following points:
- Is there a good reason to even have the option to disable this?
- When having this option disabled, there seems to be a bug somewhere (see error above)
- I think the implementation (`forbidden_chars`, `utils.sanitize_name`) may be vulnerable to directory traversal, as `.` is always allowed in filenames

**Comment by lhoenig** [comment]
> Also, I actually found a course having ".." in its title: https://isis.tu-berlin.de/course/view.php?id=30165 But cannot test it at the moment due to the error above..

The course has a ".." in its title, but I forgot that the short title is used for the directory name, so for this course nothing will happen.

**Comment by lhoenig** [comment]
Actually I have had a lot of courses with slashes going a long time back, but so far this never was a problem. I still have the directories for these courses and there, the '/' was simply deleted. Only now this started happening. Maybe this was recently changed and the option was assigned default value False or so?

**Comment by Emily3403** [comment]
First of all: I am quite certain the bug is already fixed in the GitHub Repo but it is not pushed to PyPI yet. You can try to clone the repo and install it as described in the [install guide](https://github.com/Emily3403/isisdl/wiki/Installation).

The bug arises because I mistakenly set `macos_forbidden_chars` to the empty set instead of `{"\0", "/"}` in this 
[commit](https://github.com/Emily3403/isisdl/commit/cea3f92820babcd89578495607b605d3d412b3a3). I fixed the issue [here](https://github.com/Emily3403/isisdl/commit/e6bbfb98b3a33cd3de589186caa58c77903f1107) but it hasn't been published to PyPI yet. I hope to get the new breaking version of isisdl out in the next few weeks but until then it might stay broken. 

I implemented this bug due to the fact that the [Wikipedia Article](https://en.wikipedia.org/wiki/Apple_File_System) states that MacOS supports Unicode 9.0 encoded in UTF-8 and in particular there is no restriction on slashes. This lead me to the assumption, that slashes would be fine for MacOS.  

In commit [e6bbfb98](https://github.com/Emily3403/isisdl/commit/e6bbfb98b3a33cd3de589186caa58c77903f1107) I reverted this change and since then this problem should be fixed. 

Which version of isisdl are you using in particular? In the newest GitHub Version this should already be fixed.
Do note however that you will need to delete the spare directories youself or delete the entire `~/isisdl` directory and re-download everything. 

The package `python-slugify` looks very nice indeed and I wished I'd knewn about it before I implemented all the logic to [handle filename sanitazition](https://github.com/Emily3403/isisdl/blob/aa96883acd90fa97da96ff6553e7ba271dd75f87/src/isisdl/utils.py#L807-L861) myself 😅 

As for the directory traversal vulnerability: I don't think it is to serious due to the fact that slashes are automatically removed and the only option for a directory traversal would be the Course `..` – of course, this special case _could_ be catched but I think it is to complicated and not worth the effort to check every course name for this exact name.

**Comment by lhoenig** [comment]
Good morning and thanks for the super fast reply!! 👍🏻

> The bug arises because I mistakenly set macos_forbidden_chars to the empty set instead of {"\0", "/"}

Now I understand - forbidden chars are always removed and on top of that there is optional sanitization. The explanation makes total sense, I can confirm `isisdl --version` showed the empty set before and now shows `{"\0", "/"}` again.
Unfortunately the exception when downloading is not fixed after re-running `isisdl --sync`. It's still the same as above. Maybe I need to completely delete the database to fix it?

I also noticed that when this exception occurs the lock file is not deleted, however it can be deleted by `isisdl` the next time it is run. Maybe not removing the lock file on exception is by design.

I ran the latest pip version 1.3.14 before and now tested with the current `main` branch, i.e. aa96883.

> MacOS supports Unicode 9.0 encoded in UTF-8 and in particular there is no restriction on slashes. This lead me to the assumption, that slashes would be fine for MacOS.

I think that would highly depend on how you do file handling/constructing paths, and also whether the Python library supports this already. Indeed, at least using Finder I can put slashes in files with no problem.

> The package python-slugify looks very nice indeed and I wished I'd knewn about it before I implemented all the logic to [handle filename sanitazition](https://github.com/Emily3403/isisdl/blob/aa96883acd90fa97da96ff6553e7ba271dd75f87/src/isisdl/utils.py#L807-L861) myself 😅

Its a problem that can have quite some edge cases I think, hence a library is quite useful, but it was also probably interesting to reimplement something similar :)

> As for the directory traversal vulnerability: I don't think it is to serious due to the fact that slashes are automatically removed and the only option for a directory traversal would be the Course .. – of course, this special case could be catched but I think it is to complicated and not worth the effort to check every course name for this exact name.

That's true that given that slashes are removed, its not as serious. The unfixed version is very likely fully vulnerable though.
Why do you think it's complicated to check for this specific name? `..` could just be replaced with `__` to avoid having to add extra handling if the sanitized course name is empty. While it's very unlikely that there will be a course with short name `..`, it is still a directory traversal vulnerability. In my case the directory above the `isisdl` download folder is my homedir, and files there could be overwritten in this scenario.

**Comment by Emily3403** [comment]
Good Morning ^^

I am very happy that my fix did indeed solve your issue :smiley: 

You will, however, have to delete the entire database and re-sync it due to the fact that paths are (currently) hard-coded in the database. It will always attempt to place the file in `/Users/…/ML1 (WS 21/22)/…` even though that is not a valid path anymore. The reasoning behind this is that the path should always already be sanitized and it should be in a valid state in the database. This assumption, of course, is not always valid, in particular when considering that one could change the sanitization policy. This is one of the things I am aiming to change with the new database update.

Not deleting the lock when encountering an Exception is a feature, not a bug. If there was an exception then usually something has gone terribly bad. If isisdl is run automatically, then it will most likely encounter this exception every time. Since it also dumps errors into `~/isisdl/.errors` this directory will accumulate many files and, if you don't notice it, it could lead to thousands of files being created. Of course, it could be detected that systemd is not available under MacOS and that reasoning would not work but there might be some other edge cases I did not consider. So I'll probably leave it as it is.

Interesting that you can indeed create files with slashes in them with Finder but probably it has to go through some extra magic that is not implemented in python. It might, however, be that Finder is just saying there is a slash in there [even though there isn't](https://apple.stackexchange.com/a/283095). Also having slashes in your names is _really_ bad if you would ever try to backup your files on a non MacOS machine or use them in Linux. So I'll probably just stick with deleting slashes in MacOS due to compatibility. 

For the Library I usually try to avoid external dependencies whenever possible due to the fact that I usually can't check the entire code base that is contained within the package. In particular I'd either have to make big `try: … except: …` blocks around the functions becuase they _might_ throw exceptions (thanks python and unchecked exceptions …) or read the entire code and verify there are no exceptions being thrown, but in big packages (e.g. requests or urllib) this is not really an option. For python-slugify at least it is totally doable and it is not to different from my implementation. Maybe a bit more regex, but it e.g. does not consider that a `.` at the end of a directory name is forbidden in windows. And yes, there _are_ courses that fall into that category and have to be sanitized.

Nevertheless I think I have a very good approach in sanitizing filenames due to the fact that I first enforce ASCII letters (all unicode is replaced with a `?`) and then handle all ASCII special characters that are forbidden in various filesystems. This approach _should_ be robust enough that no malicious actor could crash isisdl.

**Comment by Emily3403** [comment]
Btw a patched version of isisdl is now available on PyPI as 1.3.15 and it contains a fix for the directory traversal vulnerability – it was not to hard to implement but my tired brain yesterday couldn't think of an elegant way to do this ^^

**Comment by lhoenig** [comment]
Thanks for all the info and the quick fix! Great work, much appreciated.

Agree that slashes in filenames should best be avoided - too experimental.

Everything works again after deleting and recreating the database 👍🏻
