### ISSUE TITLE
Filename conflict not detected

### ISSUE THREAD

**Issue by l3d00m** [Emily3403/isisdl#17]
Hi,
I'm enrolled in https://isis.tu-berlin.de/course/view.php?id=31139 (Logik, should be publicly enrollable). There is a file called "[freiwillige Hausaufgabe 01 Datei](https://isis.tu-berlin.de/mod/resource/view.php?id=1460309)", which has the filename `ha01.pdf` and another file called [1. Hausarbeit Datei](https://isis.tu-berlin.de/mod/resource/view.php?id=1478564) which has the same filename `ha01.pdf`.

According to the wiki of isisdl, this should be detected right? Unfortunately it isn't and zhere is only one file called `ha01.pdf` in the download folder of isisdl. With every download isisdl seemingly picks one by random and re-downloads it (probably due to race conditions it changes). 

Is there a way to fix that? If you're not able to reproduce it based on my information, I'm happy to provide more logs.

```
> isisdl -v 
isisdl version 1.3.14

Running on Linux
This is the compiled version

working directory: /home/thomas/Documents/uni/isisdl
python executable: /home/thomas/Documents/uni/isisdl/Logik/isisdl

database_version = 2
has_ffmpeg = True
forbidden_chars = {'/', '\x00'}
fstype = 'ext4'

> uname -a
Linux thomas-manjaro 6.0.8-1-MANJARO #1 SMP PREEMPT_DYNAMIC Thu Nov 10 20:52:34 UTC 2022 x86_64 GNU/Linux
```

```
# Part of isisdl logs
Name: 'ha01.pdf'
Course: 31139
Size: 121.11 KiB
Time: 2022-10-23 22:16:09
Is downloaded: True
Path: /home/thomas/Documents/uni/isisdl/Logik/ha01.pdf

# ...... other files

Name: 'ha01.pdf'
Course: 31139
Size: 145.83 KiB
Time: 2022-11-25 11:58:14
Is downloaded: False
Path: /home/thomas/Documents/Uni/isisdl/Logik/ha01.pdf
```

**Comment by Emily3403** [comment]
Thanks for the Issue however I fear there is no good way to fix this problem as it is one of the few, rare, time my heuristic about files and conflicts in them fails.

Currently, conflicts are renamed if they occupy the same path. As the two files would get the same path `~/isisdl/WiSe 202223] Logik/ha01.pdf`, they should get renamed. However, in a previous step it is checked what files are the same. This is done because sometimes the same file is uploaded many times, and we don't want them occupying useless disk space. 

To determine if two files are the same, two heuristics are used: The download url is the same or `name`, `size` and `course_id` are all the same. For these two files something very extraordinary has happened: The `name`, `size` and `course_id` are all the same even though the file itself is _not_ the same. From my testings I can say that there are only a handful of files hosted in the entirety of ISIS where this happens. 

Unfortunately there isn't much more information available to better determine if two files are the same. You could of course request a bit of every file in the "building request cache" phase, however this is very inefficient and this phase is going to be deprecated in the next 1.4 update of `isisdl`. In fact, `isisdl` used to work in this fashion where every url was checked for content and only if the start and exponential samples of the files would all match it would be the same file. 

This is not done anymore since I want it to be possible to download the _entirety_ of ISIS with `isisdl` and spawning an extra request for every file is too much overhead with the hundreds of thousands of different files that are hosted on ISIS.

If you are interested, these are the attributes that are available for every file that is downloaded via the moodle API:

```
'type', 'filename', 'filepath', 'filesize', 'fileurl', 'timecreated', 'timemodified', 'sortorder', 'mimetype', 'isexternalfile', 'userid', 'author', 'license'
```

If you have any idea on how this conflict _could_ be detected I would gladly appreciate any feedback, but I really don't see any possibility with the given constraints.

The only thing I _can_ promise is that the conflict will be deterministically resolved in the 1.4 update. Currently, [it is iterated through a python dictionary](https://github.com/Emily3403/isisdl/blob/68016667437a9a71afa2fd1810453a7e9a01efde/src/isisdl/backend/request_helper.py#L1004-L1005) and the first file that matches "is the file". Thus, it can randomly occur that sometimes the "1. freiwillige Hausaufgabe" or sometimes the "1. Hausarbeit" is downloaded. In the future the conflict is sorted by the url string, and it will be deterministically resolved. Thus, no re-downloading of files should occur, but you will only be able to download one of the two files.

**Comment by l3d00m** [comment]
Hi, I appreciate your in-depth reply!! I do understand how it works now, thank you :)

But do the files really have the same file size though? When I curl both of them, they return different Content-Length and also the stored files on disk are different sizes, which is also shown in the isisdl.log I posted above. I posted the curl output below. 

I'm looking forward to 1.4 :)

```
curl --head https://isis.tu-berlin.de/pluginfile.php/2451837/mod_resource/content/2/ha01.pdf -H 'Cookie: Censored'

HTTP/1.1 200 OK
Date: Sun, 27 Nov 2022 19:18:54 GMT
Server: Apache
Content-Disposition: inline; filename="ha01.pdf"
Cache-Control: private, max-age=21600, no-transform
Expires: Mon, 28 Nov 2022 01:18:54 GMT
Pragma:
Accept-Ranges: bytes
X-XSS-Protection: 1; mode=block
Strict-Transport-Security: max-age=31536000; includeSubDomains
Last-Modified: Fri, 25 Nov 2022 10:58:14 GMT
Content-Length: 149326
X-Content-Type-Options: nosniff
X-Frame-Options: sameorigin
Content-Type: application/pdf
```

```
curl --head 'https://isis.tu-berlin.de/pluginfile.php/2429634/mod_resource/content/1/ha01.pdf' -H 'Cookie: Censored'

HTTP/1.1 200 OK
Date: Sun, 27 Nov 2022 19:16:56 GMT
Server: Apache
Content-Disposition: inline; filename="ha01.pdf"
Cache-Control: private, max-age=21600, no-transform
Expires: Mon, 28 Nov 2022 01:16:56 GMT
Pragma:
Accept-Ranges: bytes
X-XSS-Protection: 1; mode=block
Strict-Transport-Security: max-age=31536000; includeSubDomains
Last-Modified: Sun, 23 Oct 2022 20:16:09 GMT
Content-Length: 124018
X-Content-Type-Options: nosniff
X-Frame-Options: sameorigin
Content-Type: application/pdf
```

**Comment by Emily3403** [comment]
Okay, fair enough I had a little oversight with the explanation. I first `wget` the file from ISIS and they had the same size. If I open them in `vim`, I now realize why: They are simply the login mask from ISIS and that is why they are the same size.

I also checked on the Branch `BreakingDatabaseChanges` on how I plan to implement the new function and there the files also had the same size. This is a bug with the current implementation of Enums capturing values and I'll get around to fixing that. But in the debugger they actually had the same size 😅

Then the problem is only that dictionary that I previously mentioned and it can be safely removed. With this change, the `ha01.pdf` is split into two files: `ha01.0.pdf` and `ha01.1.pdf` , sorted by time. Thus, they _should_ be deterministically sorted and not re-downloaded. 

If you want, you can already download the fix from the `main` GitHub branch. Once the tests are through, I will publish it to PyPI.
You can install it to your local pip with 
```
pip install git+https://github.com/Emily3403/isisdl
```

And don't forget to synchronize the database due to filename updates with
```
isisdl --sync
```

**Comment by l3d00m** [comment]
I tested it over the last days and it does work perfectly now, thanks a lot. It now re-downloads much less often and no longer has issues detecting duplicate files. I guess it'd be a good idea to push the fix to PyPi as well, so others can profit from it too. 

Really appreciate your work on this!!

**Comment by Emily3403** [comment]
Yes and no. There are automatic tests with the GitHub CI which are not succeeding because they are timeouting. Unfortunately I currently do not have the time to fix this issue so I guess I will just upload it to PyPI and call it a day.
